apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
  type: LoadBalancer  # Exposes PostgreSQL externally
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
